# Generated by Django 5.1 on 2024-08-29 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_rename_property_type_property_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='date_paid',
            new_name='payment_date',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='number_of_units',
            new_name='units',
        ),
        migrations.AlterField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.tenant'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='contact_details',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property'),
        ),
    ]
