# Generated by Django 5.1 on 2024-08-31 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_payment_amount_alter_payment_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
